### ISSUE TITLE
Generate point cloud

### ISSUE THREAD

**Issue by TuskAW** [karoly-hars/DE_resnet_unet_hyb#5]
I am getting good results testing on my image set. I am wondering how I can generate a point cloud from the depth displayed with show_img_and_pred. Any advice will be much appreciated.

**Comment by karoly-hars** [comment]
I am glad you are getting good results.

Creating a point-cloud from a depth estimation is not a trivial task. I attempted to do something like this in one of my other repos: https://github.com/karoly-hars/3D_scene_reconstruction_CNNs. The results are not bad but also not that great and in order to make it work you need to know some of the camera params.

If you are trying to create a 3D environment from a depth estimation, using stixels (https://www.google.com/search?q=stixels&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj4tuel0NTqAhXWvosKHQ8nBvYQ_AUoAXoECAwQAw&biw=1853&bih=949) is probably a better approach.

**Comment by TuskAW** [comment]
Thank you very much for the information! This gives me a good starting point for what I am trying to do.
